apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
  - role: worker
  - role: worker
networking:
  disableDefaultCNI: true
  apiServerAddress: 192.168.1.200
  apiServerPort: 6443
  podSubnet: "10.0.0.0/17"
  serviceSubnet: "10.0.128.0/17"
